spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=dbedu;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12

  devtools:
    restart:
      poll-interval: 1s

  jpa:
    show-sql: true
    #    generate-ddl: true
    #    properties:
    #      hibernate:
    #        hbm2ddl:
    #          auto: update
    hibernate:
      ddl-auto:none

# Mail
mailServer:
  host: smtp.gmail.com
  port: 587
  email: hoangtuananh1772003@gmail.com
  password: vligdsqcyeaqlcex
  protocol: smtp
  isSSL: false

# Swagger3
config:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://edu-api.com

springdoc:
  swagger-ui:
    path: /edu-documentation
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true
  api-docs:
    path: /edu-api-docs
  packages-to-scan: com.huce.edu.controllers


server:
  port: 8080
  max-http-request-header-size: 10000000

###
#config jwt

jwt:
  base64-secret: TRrx3ZoD9xgevlM73MU8/ay9VO+8RJ7NjvFh5Ab0xoTsKzuPYwCOKDZugGYsVxroYRfP94DH6jBxBhFyBPaQQQ==
  #expiration : 1 day (seconds = 24 * 60 * 60)
  # 100 days
  token-validity-in-seconds : 8640000
#
###
